### ISSUE TITLE
About test phase image

### ISSUE THREAD

**Issue by YuqiHUO** [ChaojianYu/Hierarchical-Bilinear-Pooling#5]
First, thank you about the HBP model, I have some question about how do you crop image about test image in CUB. You said that 'Only center cropping is involved during inference', but it seems that you should first resize your test image to some size right? What size is it? is it 512*512 and then center crop a 448*448?

**Comment by YuqiHUO** [comment]
when i said 512 x 512 i mean 512 x S(S is the larger side)

**Comment by ChaojianYu** [comment]
yes, it is 512 * S and then center crop a 448*448

**Comment by YuqiHUO** [comment]
thanks

**Comment by ChaojianYu** [comment]
@YuqiHUO  By the way, we use 512*512 on Car and Aircraft dataset, which is better.

**Comment by YuqiHUO** [comment]
But the Car and Aircraft dataset are rectangular images, so you just resize to 512x512 arbitrarily?

**Comment by ChaojianYu** [comment]
yes, that's it, which can get better accuracy
